### ISSUE TITLE
Ressource Calculation error

### ISSUE THREAD

**Issue by Yolanda22** [Thisishowwedoit/2Moons-Revolution-2.0#1]
I have a calculation Error
scr.hu/2h9s/u8201

**Comment by Thisishowwedoit** [comment]
are all ingame bonus reset for your account. all academy. all peacefull levels. all possible thing that increase the production ?

**Comment by Yolanda22** [comment]
all is 0 and now i have a right calculation its a formula error with the extras

**Comment by ScruffyKnight** [comment]
game speed is the issue here. The top number doesn't update using the game speed setting. But the bottom half does.

**Comment by Thisishowwedoit** [comment]
can you send screen of level 40 metal on the information page yolanda?/

**Comment by Yolanda22** [comment]
http://scr.hu/2h9s/102g6 with a little bit bonuse
