### ISSUE TITLE
Reset players count

### ISSUE THREAD

**Issue by calzon11** [Thisishowwedoit/2Moons-Revolution-2.0#13]
Hi, how to reset players count?
i got this:
Server Status
players: 406
New this month: 1
New HOF: 0
active players: 406

Already reset universe in administration panel, but still count players that, also i cant see other players in database, only admin and another account by myself. New player has ID 406...

Another issue, under system message i got 70+ messages every time event start... like this:
Treasure Hunt has started.
Asteroid Event started
All inactive planets are full of resources and fleets

Thanks for help.

**Comment by merlint0** [comment]
I have same trabl, how it fix ?
