### ISSUE TITLE
Registration error

### ISSUE THREAD

**Issue by wrath76** [Thisishowwedoit/2Moons-Revolution-2.0#15]
Hay i've installed the script as per instructions, every thing works great except for the registration. when you hi submit i get a error 

Fatal error: Uncaught exception 'ErrorException' with message 'Undefined offset: 8192' in /home/techsup0/public_html/empires/includes/GeneralFunctions.php:791 Stack trace: #0 /home/techsup0/public_html/empires/includes/GeneralFunctions.php(791): errorHandler(8, 'Undefined offse...', '/home/techsup0/...', 791, Array) #1 [internal function]: exceptionHandler(Object(ErrorException)) #2 {main} thrown in /home/techsup0/public_html/empires/includes/GeneralFunctions.php on line 791

when i open generalfunctions.php...line 791 says    !--[if (gt IE 9)|!(IE)]>
may u please help.

**Comment by Xnova24** [comment]
I would remove all of the ifa.
Then it should be ok.

2016-09-23 18:46 GMT+02:00 wrath76 <notifications@github.com>:

**Comment by wrath76** [comment]
thanks.......but wheres / what is ifa ....thanks......and sorry for noob question

**Comment by wrath76** [comment]
hay xnova may u please explain

**Comment by lordspike** [comment]
Xnova24 

**# I need help, which is specifically what needs to be erased. Help me**

line 791	<title>'.$gameName.' - '.$errorType[$errno].'</title>
	<meta name="generator" content="2Moons '.$VERSION.'">
	
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="'.$DIR.'/styles/resource/css/base/boilerplate.css?v='.$VERSION.'">
	<link rel="stylesheet" type="text/css" href="'.$DIR.'/styles/resource/css/ingame/main.css?v='.$VERSION.'">
	<link rel="stylesheet" type="text/css" href="'.$DIR.'/styles/resource/css/base/jquery.css?v='.$VERSION.'">
	<link rel="stylesheet" type="text/css" href="'.$DIR.'/styles/theme/gow/formate.css?v='.$VERSION.'">
	<link rel="shortcut icon" href="./favicon.ico" type="image/x-icon">
	<script type="text/javascript">
	var ServerTimezoneOffset = -3600;
	var serverTime 	= new Date(2012, 2, 12, 14, 43, 36);
	var startTime	= serverTime.getTime();
	var localTime 	= serverTime;
	var localTS 	= startTime;
	var Gamename	= document.title;
	var Ready		= "Fertig";
	var Skin		= "'.$DIR.'/styles/theme/gow/";
	var Lang		= "de";
	var head_info	= "Information";
	var auth		= 3;
	var days 		= ["So","Mo","Di","Mi","Do","Fr","Sa"] 
	var months 		= ["Jan","Feb","Mar","Apr","Mai","Jun","Jul","Aug","Sep","Okt","Nov","Dez"] ;
	var tdformat	= "[M] [D] [d] [H]:[i]:[s]";
	var queryString	= "";

	setInterval(function() {
		serverTime.setSeconds(serverTime.getSeconds()+1);
	}, 1000);
	</script>
	<script type="text/javascript" src="'.$DIR.'/scripts/base/jquery.js?v=2123"></script>
	<script type="text/javascript" src="'.$DIR.'/scripts/base/jquery.ui.js?v=2123"></script>
	<script type="text/javascript" src="'.$DIR.'/scripts/base/jquery.cookie.js?v=2123"></script>
	<script type="text/javascript" src="'.$DIR.'/scripts/base/jquery.fancybox.js?v=2123"></script>
	<script type="text/javascript" src="'.$DIR.'/scripts/base/jquery.validationEngine.js?v=2123"></script>
	<script type="text/javascript" src="'.$DIR.'/scripts/base/tooltip.js?v=2123"></script>
	<script type="text/javascript" src="'.$DIR.'/scripts/game/base.js?v=2123"></script>
</head>
<body id="overview" class="full">
<table width="960">
	<tr>
		<th>'.$errorType[$errno].'</th>
	</tr>
	<tr>
		<td class="left">
			<b>Message: </b>'.$exception->getMessage().'<br>
			<b>File: </b>'.$exception->getFile().'<br>
			<b>Line: </b>'.$exception->getLine().'<br>
			<b>URL: </b>'.PROTOCOL.HTTP_HOST.$_SERVER['REQUEST_URI'].'<br>
			<b>PHP-Version: </b>'.PHP_VERSION.'<br>
			<b>PHP-API: </b>'.php_sapi_name().'<br>
			<b>MySQL-Cleint-Version: </b>'.mysqli_get_client_info().'<br>
			<b>2Moons Version: </b>'.$VERSION.'<br>
			<b>Debug Backtrace:</b><br>'.makebr(htmlspecialchars($exception->getTraceAsString())).'
		</td>
	</tr>
</table>
</body>
line 854 </html>';

**Comment by Xnova24** [comment]
2017-01-29 1:14 GMT+01:00 lordspike <notifications@github.com>:

> <title>'.$gameName.' - '.$errorType[$errno].'</title>


Witaj.
Usuń całą tą linijkę i będzie ok.
<title>'.$gameName.' - '.$errorType[$errno].'</title>

Pozdrawiam Andrzej
