### ISSUE TITLE
 Sorry my what a forum get an error

### ISSUE THREAD

**Issue by dahuf86** [Thisishowwedoit/2Moons-Revolution-2.0#2]
Quellcode

    Message: SQL Error: Table 'xnova.forum_topics' doesn't exist
    Query Code: SELECT tid, title, last_post, topic_firstpost, title_seo FROM forum_topics WHERE tdelete_time = '0' ORDER BY last_post DESC LIMIT 5;
    File: /includes/classes/class.Database.php
    Line: 80
    URL: http://xnova2.de/v1/
    PHP-Version: 5.3.3-7+squeeze19
    PHP-API: cgi-fcgi
    MySQL-Cleint-Version: 5.1.73
    2Moons Version: 1.7.2676
    Debug Backtrace:
    #0 /includes/pages/login/ShowIndexPage.class.php(99): Database->query('SELECT tid, tit...')
    #1 /index.php(65): ShowIndexPage->show()
    #2 {main}

**Comment by Thisishowwedoit** [comment]
Hello take some time to read this correctly

https://github.com/Thisishowwedoit/2Moons-Revolution-2.0/blob/master/README.md

**Comment by dahuf86** [comment]
not work

**Comment by Thisishowwedoit** [comment]
what not work if you cant give a clear answer then i cant help u !
do you have any basic knowledge ?

**Comment by Thisishowwedoit** [comment]
Some guy changed my invision virus logins details, so you will have to create a new account to download the forum on their site

**Comment by cohaudegen** [comment]
hi...wenn ich ip.board installieren möchte, dann öffnet sich ein neues fenster mit der  meldung:"The server made a boo boo.", was mach ich falsch?

http://community.invisionpower.com/resources/guides.html/_/install-and-getting-started/installing-r18

**Comment by Thisishowwedoit** [comment]
you can add me skype battle-fighter and install teamviewer i will help with installation
