### ISSUE TITLE
statistics not work

### ISSUE THREAD

**Issue by dahuf86** [Thisishowwedoit/2Moons-Revolution-2.0#3]
the statistics of the usern not work all remain at 0 is emptied cach cronjob runs

**Comment by Thisishowwedoit** [comment]
what you have as notice ?

**Comment by ScruffyKnight** [comment]
Goto cron tab, turn on stats update. 
Value of statistical point 1 (resources) : 1
	
Points to "0" (will not appear in points statistics): do not display admins
	
Access level: 3

goto Update Stats on dash board and run. 

If that works edit Value of statistical point 1 (resources) : 1 to a higher value (recommend 150,000+)

**Comment by dahuf86** [comment]
have as yet an error

city rang 1 2 3 are now only displayed *

**Comment by Thisishowwedoit** [comment]
you have to keep the admin displayed. else it will not work, so every one see admin is not a player
