### ISSUE TITLE
Обнуление вселенной

### ISSUE THREAD

**Issue by Gordon-Freeman-hev** [Thisishowwedoit/2Moons-Revolution-2.0#7]
Как полностью обнулить вселенную? Я несколько раз делал это стандартными средствами игры, но вселенная полностью не обнулилась. Достижения не обнулились. "Мирный" и "Военный" уровни остались прежними. Некоторые бонусы никуда не исчезли.

**Comment by Thisishowwedoit** [comment]
только основной материал Вселенной сбрасываются

В остальном, вам нужно сбросить это вручную из базы данных

**Comment by Gordon-Freeman-hev** [comment]
В какие таблицы нужно вносить изменения?
