### ISSUE TITLE
Dudes

### ISSUE THREAD

**Issue by Alberolle7** [Thisishowwedoit/2Moons-Revolution-2.0#9]
First, thank you very much for this code, is a big job, if I can earn some thanks to you I would like to give you a part of it.
I have some doubts have if Might help. There is something called Fortness, but can not find any information concerning it. Could you please tell me which are the missing to end or contain errors parts?
Could you please tell me also if some images are copyrighted?
The chat does not work, is the same as 2moons?
I will have many problems in passing a database 2moons this code?
What is Hostal sector?
You will keep updating the code? I would like to keep in touch with you
Thank you very much, translated with google translator

**Comment by Thisishowwedoit** [comment]
chat just activate it in admin panel
fortress is something that will come but later, have no time actualy to finish it with irl
It will be updated if xterium.ru updates
its a repack from xterium.ru, i dont thin the images are copyrighted, to be honest i dont care about copyrights :)

**Comment by Gordon-Freeman-hev** [comment]
У меня есть вопрос к разработчику. Каким образом вы получили движок Xterium?

**Comment by Yolanda22** [comment]
The fortress mod is complete the last edit is written intro 20 mins 
By me work this fine
